alias -g ls='ls -G'
alias -g ll='ls -hl'
alias -g l='ls -l'
alias -g lht='ls -lht'
alias -g la='ls -la'
alias -g ...='cd ..'
alias -g c='clear'
alias -g reload='source ~/.zshrc'
alias -g gs='echo "do not fuck with me asshole!"'
alias -g gst='git status'
alias -g gaa='git add .'
alias -g gcam='git commit -a'
alias -g gcam.='git commit -am "an internal commit! ;)"'
alias -g gck='git checkout'
alias -g gb='git branch'
alias -g gpprod='git pull --rebase origin production --tags'
alias -g gpmaster='git pull --rebase origin master --tags'
alias -g gl='git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)%an%Creset" --abbrev-commit'
alias -g mci='mvn clean install'
alias -g mcp='mvn clean package'
alias -g gpl='git pull --rebase'
alias -g gps='git push'
alias -g grb='git rebase'
alias -g gmg='git merge'
alias -g k='gitk'
alias -g pcat='pygmentize -f terminal256 -O style=native -g'
alias -g hosts='E /etc/hosts'
alias -g n="node"
alias -g E="SUDO_EDITOR=\"emacs -nw --no-splash\" sudoedit"
alias -g vi="XMODIFIERS=\'\' emacs -nw --no-splash"
alias -g sk9='sudo kill -9'
alias -g psg='ps aux | grep'
alias -g ee="(XMODIFIERS=\'\' nohup emacs --no-splash >&/dev/null &)"
