alias -g ls='ls -G'
alias -g ll='ls -hl'
alias -g l='ls -l'
alias -g lht='ls -lht'
alias -g la='ls -la'
alias -g ...='cd ..'
alias -g c='clear'
alias -g reload='source ~/.zshrc'
alias -g gs='echo "do not fuck with me asshole!"'
alias -g gst='git status -sb'
alias -g gaa='git add .'
alias -g gcam='git commit -m'
alias -g gcam.='git commit -am "an awesome commit! ;)"'
alias -g gck='git checkout'
alias -g gckb='git checkout -b'
alias -g gb='git branch'
alias -g gpm='git pull --rebase origin master --tags'
alias -g gl='git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)%an%Creset" --abbrev-commit'
alias -g mci='mvn clean install'
alias -g mcp='mvn clean package'
alias -g gpl='git pull'
alias -g gps='git push'
alias -g gplo='git pull origin'
alias -g gpso='git push origin'
alias -g grb='git rebase'
alias -g gmg='git merge'
alias -g k='gitk'
alias -g hosts="sudo XMODIFIERS=\'\' $EDITOR /etc/hosts"
alias -g n="node"
alias -g E="sudo $EDITOR "
alias -g vi="XMODIFIERS=\'\' emacs -nw --no-splash"
alias -g vii="XMODIFIERS=\'\' emacs -nw --no-splash --no-init-file"
alias -g sk9='sudo kill -9'
alias -g psg='ps aux | grep'
alias -g ee="(XMODIFIERS=\'\' nohup emacs --no-splash >&/dev/null &)"
